spring:
  #静态资源处理
  resources:
    cache:
      cachecontrol:
        #缓存响应时间
        max-age: 3600
    chain:
      #资源链启用缓存
      cache: true
      #启动资源链
      enabled: true
      #压缩资源(gzip,brotli)
      compressed: true
      #启用h5应用缓存
      html-application-cache: true
    #资源链
    #启用静态默认资源处理
    add-mappings: true
    static-locations: classpath:/static/
  #thymeleaf配置
  thymeleaf:
    #关闭缓存
    cache: false
  #数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.255.128:3306/seckill?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: hzc
    password: root #windodw的密码是root,linux的密码是1234
    #连接池名
    hikari:
      pool-name: DateHikariCp
      #最小空闲连接
      minimum-idle: 5
      #空闲连接存活最大时间,默认是 10*60
      idle-timeout: 180000
      #最大连接数量,默认是10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #最大存活时间,赋值为0表示永久存活,默认为半小时
      max-lifetime: 180000
      #连接超时时间,默认30s
      connection-timeout: 30000
      #心跳机制，查询连接是否可用的测试机制
      connection-test-query: SELECT 1
  #redis配置
  redis:
    #服务器地址
    host: 192.168.255.128
    #端口
    port: 6379
    #数据库
    database: 0
    #连接超时时间
    connect-timeout: 10000ms
    lettuce:
      pool:
        #默认连接数量
        max-active: 8
        #最大连接阻塞等待时间,默认-1一直等待
        max-wait: 10000ms
        #最大空闲时间
        max-idle: 200
        #最小空闲时间
        min-idle: 5
  #rabbitmq
  rabbitmq:
    #服务器
    host: 192.168.255.128
    #用户名,默认也是gues
    username: guest
    #密码
    password: guest
    #虚拟主机
    virtual-host: /
    listener:
      simple:
        #消费者最少数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #消费者每次处理一条消息
        prefetch: 1
        #启动时默认启动容器
        auto-startup: true
        #被拒绝时是否进入队列
        default-requeue-rejected: true
    template:
      retry:
        #发布重试默认 false
        enabled: true
        #重试时间,默认为1000ms
        initial-interval: 1000ms
        #重试最大次数默认3
        max-attempts: 3
        #重试最大时间默认为10s
        max-interval: 10000ms
        #重试的间隔乘数,下一次等待时间是上一次的n倍
        multiplier: 1
      #发布重试,默认为false
    port: 5672

mybatis-plus:
  #配置xxxmapper.xml的映射位置可以用resource下com.hzc.mapper代替
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置别名
  type-aliases-package: com.hzc.seckill.pojo
#mybatis方法接口所在的包，不是resource包(里面放了mapper文件)
logging:
  level:
    com.hzc.seckill.mapper: debug
server:
  port: 8080